### ISSUE TITLE
mongoapi:save of a map fails with function_clause

### ISSUE THREAD

**Issue by gotthardp** [SergejJurecko/erlmongo#44]
First of all, many thanks for your effort.

In the mongoapi:save the oid is prepended to the document being saved:
https://github.com/SergejJurecko/erlmongo/blob/master/src/mongoapi.erl#L37

This works fine for proplists, but if I save a map, then bson:encode fails, because all elements are expected to be `{Name, Value}` tuples.

I believe that if `L` is a map, you should do `L#{<<"_id">> => {oid, OID}}` instead.

**Comment by SergejJurecko** [comment]
Thank you very much for reporting the issue.
