### ISSUE TITLE
SSL support?

### ISSUE THREAD

**Issue by Spoowy** [SergejJurecko/erlmongo#48]
Hello,
it seems like I am unable to establish a connection and a part of the reason could be that I am using MongoDB Atlas and need to establish a ssl connection.

Although I changed the tcp connections to ssl connections, I cannot get my replicaSet connected. The constant "reconnect-reattempt" stopped though.

Grateful for any advice!

Cheers,
Erwin

**Comment by SergejJurecko** [comment]
There is no ssl support at this time

**Comment by Spoowy** [comment]
Ok, does the auth logic use authSource=admin?
`{find, Source, <<"admin.$cmd">>,` leads me to believe that. 

https://github.com/SergejJurecko/erlmongo/blob/master/src/mongodb.erl#L808

If not, then that could be another reason for my authentication failure.

**Comment by Spoowy** [comment]
yep! Got a connection established with ssl. Wonderful!

I do have a side-question regarding to mongoapi. I get an error when I do:
```
Mong = mongoapi:new(mongo_pool,<<"mws">>).
Mong:count("user").          
** exception error: bad argument
     in function  apply/3
        called as apply({mongoapi,[mongo_pool,<<"mws">>]},count,["user"])
```
But it works when doing
```
mongoapi:count("user", Mong).
```

Any suggestions to why this may?

**Comment by SergejJurecko** [comment]
Erlang 21 disabled tuple calls. You must call with mongoapi and last parameter Mong.

**Comment by Spoowy** [comment]
Great! Do you want a PR with ssl capabilities? I'm just thinking where to put the config val for the driver that sets ssl.

**Comment by SergejJurecko** [comment]
Sure

**Comment by Spoowy** [comment]
https://github.com/SergejJurecko/erlmongo/pull/49
