### ISSUE TITLE
logo design proposal

### ISSUE THREAD

**Issue by Tobaloidee** [SergejJurecko/erlmongo#50]
Hi @SergejJurecko  Good day! I am a graphics artist and would like to contribute a logo design for the project to make it more visible. I just need your permission first before i begin.Hoping for your positive feedback.Best regards! - [Tobaloidee](https://steemit.com/@tobaloidee)

**Comment by SergejJurecko** [comment]
Sure if you want.

**Comment by Tobaloidee** [comment]
hi @SergejJurecko  here's what i came up with..still open for suggestions
![initial design-01](https://user-images.githubusercontent.com/36028424/54902684-04814900-4f15-11e9-8afd-eae4380ef218.png)

**Comment by SergejJurecko** [comment]
heh looks pretty good

**Comment by Tobaloidee** [comment]
i'll prepare the files and make a PR SergejJurecko 👍

**Comment by Tobaloidee** [comment]
Hi @SergejJurecko  I have uploaded the logo and updated the readme (i hope i did it right in .Rdoc) hehe
here's the PR #51 Thanks a lot and best regards!
