### ISSUE TITLE
How is this installed?

### ISSUE THREAD

**Issue by limenleap** [SergejJurecko/erlmongo#52]
I would appreciate if you can let me know how to install this module in Ubuntu (I use 19.04)  I tried running make, but there was no make file.  

I got as far as this

rebar co 

and it did some compilation. But not sure what else to do (I am a newbie in Erlang)

**Comment by SergejJurecko** [comment]
This is used as a dependency to your main erlang project whatever you are doing. Not installed system-wide.

In your main project add rebar.config if you do not have it already. Then add erlmongo to deps.

{deps,[
{erlmongo,".*",{git,"https://github.com/SergejJurecko/erlmongo.git",{branch, "master"}}}
]}.
