### ISSUE TITLE
How do I perform an aggregate query

### ISSUE THREAD

**Issue by dadaxixiyou** [SergejJurecko/erlmongo#54]
I want to count the total amount，how i can use $sum?
Now i use mongdb 4.0

**Comment by SergejJurecko** [comment]
With a command

https://docs.mongodb.com/v3.2/reference/command/aggregate/

`
mongoapi:runCmd([
        {"aggregate", "collection"},
        {"cursor", #{ } },
        {"pipeline",
            {array,[
                [
                  {"$match", MatchQuery} 
                ],
                [{"$unwind", "$tags"}],
                [
                  {"$group",[
                               {"_id","$tags"}
                            ]}
                ]
            ]}
        }
      ], M)
`

**Comment by dadaxixiyou** [comment]
thank you so much, i try it.
Multiple table updates can also be done with commands instead of transactions, right?

**Comment by SergejJurecko** [comment]
Yeah probably, I have not checked

**Comment by dadaxixiyou** [comment]
ok, thank you~

**Comment by dadaxixiyou** [comment]
mongoapi:runCmd([
        {"aggregate", ?ORDER_TABLE},
        {"cursor", #{ } },
        {"pipeline",
            {array,[
                [
                    {"$match", #{status=>0}}
                ],
                [
                    {"$group",[
                        {"_id","null"},
                        {"total", [{"$sum", "$amount"}]}
                    ]}
                ]
            ]}
        }
    ], ?MONGO_MASTER),

the query result is:
[{<<"cursor">>,
               [{<<"firstBatch">>,
                 {array,[[{<<"_id">>,<<"null">>},{<<"total">>,1900}]]}},
                {<<"id">>,0},
                {<<"ns">>,<<"paycenter_db.pay_order">>}]},
              {<<"ok">>,1.0}]

Can you give me a correct demonstration?
Cursor is a mandatory parameter, but I am not sure how to use it. Do I need to close cursor?
