### ISSUE TITLE
worry~  why Only one CPU is used

### ISSUE THREAD

**Issue by dadaxixiyou** [SergejJurecko/erlmongo#57]
Why is my mongodb server only one CPU is used?

**Comment by SergejJurecko** [comment]
I'm not a mongodb server developer.

**Comment by dadaxixiyou** [comment]
Thank you for your quick reply,
How do I use master-slave?  
mongodb:masterSlave(mongodb_master, "127.0.0.1:27017", "127.0.0.1:27017"),
    mongodb:connect(mongodb_master),
