### ISSUE TITLE
How can I update multiple fileds?

### ISSUE THREAD

**Issue by AbhishekLYK** [SergejJurecko/erlmongo#59]
I have 4 docs in a collection like following
{ "_id" : 1, "name" : "A", "age" : 10 }
{ "_id" : 2, "name" : "B", "age" : 20 }
{ "_id" : 3, "name" : "C", "age" : 20 }
{ "_id" : 4, "name" : "B", "age" : 40 }

And I want to update age of all to 50 whose name is "B" via multi. Please help.

**Comment by SergejJurecko** [comment]
call update with multi flag

**Comment by AbhishekLYK** [comment]
Thanks for your reply. I am new to this library. Please help me with sample command.

**Comment by SergejJurecko** [comment]
mongoapi:update(MyCollection,
      [{<<"name">>,<<"B">>}], 
      [{<<"age">>, 50}], [multi], MongoConn),

**Comment by AbhishekLYK** [comment]
I tried with
mongoapi:update("test", #{name=><<"B">>}, #{age=><<50>>}, [multi], Mong).

but neither it's giving respose nor updating

**Comment by AbhishekLYK** [comment]
Tried with you sample
mongoapi:update("test",[{<<"name">>,<<"B">>}],[{<<"age">>, 50}], [multi], Mong).

It is giving {error,[{<<"ok">>,1.0},{<<"n">>,0}]}

**Comment by SergejJurecko** [comment]
[{<<"age">>, {set,50}}]

**Comment by AbhishekLYK** [comment]
Thanks, It worked

Full command (For other's help)

mongoapi:update("test",[{<<"name">>,<<"B">>}],[{<<"age">>, {set,50}}], [multi], Mong).
